<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>criticallity_pipeline_launch</name>
  <version>0.0.0</version>
  <description>launch files for the criticallity pipeline</description>
  <maintainer email="adrian.rieker@tum.de">Adrian Rieker</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ttc_calculator</depend>
  <depend>stereo_perception_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
