ttc_calculator_node:
  launch: true
  ros__parameters:
    input_clusters_topic: "/multisense/perception_pipeline/output_clusters"
    input_twist_topic: "/stereo_perception/ego_twist"
    input_path_topic: "/stereo_perception/ego_path"
    output_ttc_topic: "/object_ttc"
    output_min_ttc_topic: "/min_ttc"
    output_marker_topic: "/ego_marker"
    ego_width: 1.0
    ego_length: 1.0
    ego_height: 1.0
    publish_ego_marker: true
    use_path: false
    output_csv_path: "/home/ubuntu/ttc_logs"

foxglove_bridge_node:
  launch: false
  ros__parameters:
    port: 8765
    use_compression: true